name: Skin Cancer Prediction CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Lint with flake8
    #- name: Lint with flake8
    #  run: |
    #    pip install flake8
    #    flake8 . --max-line-length=120 --exclude=.git,__pycache__,*.pyc

    # Run tests with pytest
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/ -v

    # Run the training script (limited epochs for CI)
    - name: Run training script
      run: |
        python src/train.py
      env:
        EPOCHS: 1  # Limit epochs for CI to save time

    # Upload artifacts (logs, plots, models)
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-outputs
        path: |
          logs/
          plots/
          models/